-- AlterTable
ALTER TABLE "CombatParticipant" ADD COLUMN     "cha" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "con" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "dex" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "hitDice" TEXT,
ADD COLUMN     "int" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "level" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "proficiencyBonus" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "speed" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "str" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "wis" INTEGER NOT NULL DEFAULT 10;
